### ISSUE TITLE
Doesn't compile on with Arduino 1.8.12?

### ISSUE THREAD

**Issue by Da-kota** [matthijskooijman/arduino-dsmr#35]
Trying to get this library to work on my Arduino Wifi Rev2 with above-mentioned environment version.

I get compile errors mentioning incompatible types 'char *'  and  '__FlashStringHelper *'.

Could you point me in the direction of a solution?
